### ISSUE TITLE
Error creating pull request: Unprocessable Entity (HTTP 422)

### ISSUE THREAD

**Issue by mrcasals** [github/hub#189]
I can't open a pull request with hub. This is what I do:

```
$ git checkout -b new_branch
( some changes here)
$ git commit -m "Test commit"
$ git push origin new_branch
$ hub pull-request
```

And this is what I get from the last command:

```
(username and password lines)
Error creating pull request: Unprocessable Entity (HTTP 422)
field 'head_sha' is missing
field 'base_sha' is missing
base No commits between user:master and user:new_branch
```

**Comment by dfd07d** [comment]
@mrcasals   +1  thanks!

**Comment by CrandellWS** [comment]
got 422 error when the base and head branch where inverted...

**Comment by Droogans** [comment]
I got a 422 error when attempting to make the POST request to `api.github.com/${upstream}/project/pulls`, instead of `api.github.com/${fork}/project/pulls`.

**Comment by jerryasher** [comment]
Sigh. My turn now.

I would like to create a pull request for the copy_file_metadata branch of my fork of getpelican/pelican back to getpelican.

My remotes are set up as follows:

```
$ git remote -v
jerryasher      git@github.com:jerryasher/pelican.git (fetch)
jerryasher      git@github.com:jerryasher/pelican.git (push)
origin  git@github.com:getpelican/pelican.git (fetch)
origin  git@github.com:getpelican/pelican.git (push)
```

git status suggests:
```
$ git status
On branch copy_file_metadata
Your branch is up-to-date with 'jerryasher/copy_file_metadata'.
nothing to commit, working directory clean
```

When I ask hub to make a pull request:

```
$ GIT_EDITOR=vi hub pull-request
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

I'm a bit lost...

**Comment by mislav** [comment]
@jerryasher Sorry you're having trouble!

1. What is your `hub version`?
2. What is your `git config push.default`?
3. You can debug with `HUB_VERBOSE=1 hub pull-request ...`. You will be able to see raw HTTP requests. What parameters is hub trying to post? What API endpoint is it trying to post to?

Sorry that this is such a mess right now. I'm working on making this easier. In the meantime, you can try using explicit head:

```
hub pull-request -h jerryasher:copy_file_metadata
```

**Comment by jerryasher** [comment]
Thanks, I won't be able to get back to this until Thursday, but I
appreciate the quick reply!

**Comment by jerryasher** [comment]
Okay, so getting back, and reading about about push.default, I do sort of think at least one issue is that my git config push.default is `simple` not `current`, but I'm also getting ```validation failed```.

So

```
$ hub --version
git version 2.8.3
hub version 2.2.8
```

git config push.default is `simple`

And hub fails with:

```
> POST https://api.github.com/repos/getpelican/pelican/pulls
> Authorization: token [REDACTED]
{"base":"master","body":"Python's shutil.copy2 fails on Android when copying a file's meta data (perm bits, access times) onto certain filesystems.\nThis is documented as python issue28141 https://bugs.python.org/issue28141\n\nThese commits workaround that bug by\n\n+ creating a new function copy_file_metadata in utils.py\n+ wrapping calls to copy2 in a try/except clause that logs any errors that occur but keep execution going\n+ changing the calls to shutil.copy2 to calls to the new function","head":"jerryasher:copy_file_metadata","title":"Python's shutil.copy2 fails on Android"}
< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

The same validation error occurs even when I  point to an explicit head.

Googling for hub authentication issues, I can't see anything I am doing/did wrong. I did login a few days back with hub. I do see a ~/.config/hub that seems to have a valid token for user: jerryasher and on github itself there is a token that is described as "hub for Jerry@mybox" that has enabled scopes: repo, repo:status, repo_deployment, public_repo

**Comment by mislav** [comment]
> The same validation error occurs even when I point to an explicit head.

Thanks for that debugging data. The parameters that hub tries to POST as a new pull request is perfectly valid. You are not able to create a pull request because, as it turns out, `jerryasher/pelican` **isn't a fork** of `getpelican/pelican`. I suggest you delete your `pelican` repo on GitHub, do `hub fork`, push your branch again (`git push jerryasher HEAD`), and try making a pull request again.

**Comment by jerryasher** [comment]
> jerryasher/pelican isn't a fork of getpelican/pelican

Well that's an interesting statement! I admit I am a novice with git and github, but if I recall the pedigree of jerryasher/pelican, I cloned it from getpelican/pelican onto my local machine, setup the remotes, and then pushed onto github. I think that's what I did, but well I'm not sure.

Is that not a fork? Are you saying it's "merely" a clone, not a fork, and if so, what were you able to look at that let you know it was a clone (or whatever it is) and not a fork?

**Comment by jerryasher** [comment]
Heh. Okay, I bet amongst other things you were looking for this: ```forked from getpelican/pelican```

**Comment by mislav** [comment]
Sorry, I didn't know you were new to GitHub.

A "fork" can mean two things, depending on the context:

1. You obtained an open source project and made changes to it. You've then created a "fork". Your changed version might not be public yet. You might choose to make it public (on a site like GitHub) or submit patches to the original maintainer(s).

2. You have forked a repository on GitHub. This is done via the "fork" button on GitHub.com or `hub fork` command. It kind of encompasses (1), but with the addition of GitHub being aware that your fork is somehow "linked" to the parent repository. GitHub pull requests are only possible from a fork to the parent repo (or another fork), or within the same repo, but they are not available between repos which aren't "linked" as forks— even though they might share the same history in git, as in your case.

**Comment by isomorphisms** [comment]
I had this error too.

**Comment by oscart** [comment]
It seems it won't accept the slash character (/) in branch name.

**Comment by minal2709** [comment]
git version 2.13.1
hub version 2.2.9

I get the same error. `Error creating pull request: Unprocessable Entity (HTTP 422)`

**Comment by TheAifam5** [comment]
yes, still the same error.

**Comment by mislav** [comment]
Anyone who is still getting the `Error creating pull request: Unprocessable Entity (HTTP 422)` error:

1. Does the error message provide any more information other than that single line?
2. If you use `HUB_VERBOSE=1 hub pull-request ...` to enable verbose mode and inspect the raw JSON server response, does it contain any more information about what went wrong?

Thank you.

**Comment by ohcibi** [comment]
@mislav I just had this because I forgot to push to my fork before `hub pull-request`. Maybe a TL;DR should added to the issue text. Main reasons why it fails:

1. Forget to push to fork
2. Forget to track fork'ed branch (i.e. `git push -u <my-remote> <my-new-branch>`)

**Comment by oblitum** [comment]
Does this still work, I tried all variations, all I can get is:

```
$ HUB_VERBOSE=1 hub pull-request -i 15 -h "oblitum:open-functionality"
$ git config alias.pull-request
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/oblitum/open-functionality
> GET https://api.github.com/repos/oblitum/extrakto
> Authorization: token [REDACTED]
< HTTP 401
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
$ git rev-list --cherry-pick --right-only --no-merges oblitum/open-functionality...
> POST https://api.github.com/repos/laktak/extrakto/pulls
> Authorization: token [REDACTED]
{"base":"master","head":"oblitum:open-functionality","issue":15}
< HTTP 401
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
Error creating pull request: Unauthorized (HTTP 401)
Bad credentials
```
```
git version 2.14.2
hub version 2.2.9
```

**Comment by pranavgarg** [comment]
In my case, it was a simple mistake of not pushing the local branch to the remote origin. 
Once I pushed the branch to GitHub was able to successfully create the pull-request using `hub`.

**Comment by fperez** [comment]
Quick note: this happens very easily if one follows to the line the [official instructions](https://hub.github.com), because those suggest using:

```bash
# push the changes to your new remote
$ git push YOUR_USER feature
```

where as they should read:

```bash
# push the changes to your new remote
$ git push -u YOUR_USER feature
```

The **`-u`** flag is missing from the instructions. This has happened already to me three or four times, and I end up here every time. There may be other causes, but I suspect if the docs are updated with that trivial fix (add `-u` to that line), at least some people won't stumble on this anymore...

**Comment by mislav** [comment]
@fperez Good catch. Mind submitting a fix for [the gh-pages branch](https://github.com/github/hub/tree/gh-pages)?

**Comment by lestephane** [comment]
Why was this closed? @fperez pointed out that the official instructions miss the crucial parameter (`-u`).
Looking at https://hub.github.com now, the flag is still missing:

```bash
# push the changes to your new remote
$ git push origin feature
```
I followed those instructions for the first time today, and, sure enough, got the 422, and landed on this issue...

**Comment by mislav** [comment]
@lestephane Are you using the latest version of hub?

This should work:

```console
$ git push origin HEAD
$ hub pull-request
```

If it doesn't, then please state some more info, such as git remote configuration and current `git config push.default` and git version. Thank you!

**Comment by lestephane** [comment]
This is what I have
```text
$ hub --version
git version 2.21.0
hub version 2.12.1
```

**Comment by mislav** [comment]
@lestephane I'm sorry, but you'll have to share more info about your error. Hub does work (this is verified by automated tests) that `git push origin HEAD` (no `-u`) and `hub pull-request` flow works in a common-use case, but the reason it does not work for you might be that part of your workflow is more specific or that there is an edge-case bug.

What I want to know is:
- How did you push the current branch before doing `hub pull-request` (I'm presuming it was `git push <REMOTE> <BRANCH>` or `git push <REMOTE> HEAD`);
- What is the git remote configuration for `REMOTE` (see `git remote -v`), you can anonymize the names of repositories if needed;
- What is the configuration for remotes named `origin`, `upstream`, and `github` (if any);
- Are you pushing your branch to a GitHub repository that is a fork?
- What is the *exact* error that you get as a result of `hub pull-request`? You can set `HUB_VERBOSE=1` to get more debugging output.

Thank you!

**Comment by lestephane** [comment]
Here is the full reproduction showing that the instructions on https://hub.github.com/ for contributing "As a contributor to open-source" are not working for me. After the reproduction, I answer each of your questions in turn. the HUB_VERBOSE=1 output can be confusing with lines starting with dollar sign ($) which could be mistaken for commands I ran myself as part of the reproduction, so I put the verbose output at the very, very end of this comment.

## Reproduction
```bash
$ hub --version
git version 2.21.0
hub version 2.12.1

$ grep "hub alias"  ~/.bashrc
eval "$(hub alias -s)"

$ git clone --depth 1 github/hub
Cloning into 'hub'...
remote: Enumerating objects: 676, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (538/538), done.
remote: Total 676 (delta 162), reused 345 (delta 101), pack-reused 0
Receiving objects: 100% (676/676), 1.42 MiB | 635.00 KiB/s, done.
Resolving deltas: 100% (162/162), done.

$ git checkout -b feature
Switched to a new branch 'feature'

$ echo -e "\nnew stuff" >> README.md

$ git commit -am "done with feature"
[feature a08a79d] done with feature
 1 file changed, 2 insertions(+)

$ git fork --remote-name=origin
renaming existing "origin" remote to "upstream"
Updating origin
remote: Enumerating objects: 17667, done.
remote: Counting objects: 100% (17667/17667), done.
remote: Compressing objects: 100% (5670/5670), done.
remote: Total 17352 (delta 11605), reused 17010 (delta 11266), pack-reused 0
Receiving objects: 100% (17352/17352), 4.80 MiB | 641.00 KiB/s, done.
Resolving deltas: 100% (11605/11605), completed with 238 local objects.
From git://github.com/github/hub
 * [new branch]        1.11-stable             -> origin/1.11-stable
 * [new branch]        1.12-stable             -> origin/1.12-stable
 * [new branch]        2.2-stable              -> origin/2.2-stable
 * [new branch]        2.7-stable              -> origin/2.7-stable
...(full branch and tag listing here)
 * [new tag]           v2.8.0                  -> v2.8.0
 * [new tag]           v2.8.1                  -> v2.8.1
 * [new tag]           v2.8.2                  -> v2.8.2
 * [new tag]           v2.8.3                  -> v2.8.3
 * [new tag]           v2.8.4                  -> v2.8.4
 * [new tag]           v2.9.0                  -> v2.9.0
new remote: origin

$ git push origin feature
Enumerating objects: 22, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 300 bytes | 100.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: 
remote: Create a pull request for 'feature' on GitHub by visiting:
remote:      https://github.com/lestephane/hub/pull/new/feature
remote: 
To github.com:lestephane/hub.git
 * [new branch]        feature -> feature

$ git pull-request
(edit the description in vim , then :wq)
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

$ git config -l | grep -v user.name | sort
alias.changes=log --name-status HEAD..
alias.up=pull --rebase --autostash
branch.master.merge=refs/heads/master
branch.master.remote=upstream
color.ui=auto
core.autocrlf=input
core.bare=false
core.editor=vim
core.excludesfile=/home/lestephane/.gitignore_global
core.filemode=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.whitespace=cr-at-eol
credential.helper=/usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
diff.tool=meld
http.postbuffer=52428800
merge.conflictstyle=diff3
merge.tool=meld
mergetool.meld.path=/usr/bin/meld
push.default=upstream
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@github.com:lestephane/hub.git
remote.upstream.fetch=+refs/heads/master:refs/remotes/upstream/master
remote.upstream.url=git://github.com/github/hub.git
user.useconfigonly=true

$ git remote -vv
origin	git@github.com:lestephane/hub.git (fetch)
origin	git@github.com:lestephane/hub.git (push)
upstream	git://github.com/github/hub.git (fetch)
upstream	git://github.com/github/hub.git (push)
```
## Answers to your questions

> How did you push the current branch before doing hub pull-request?

The way it is described at https://hub.github.com/ for contributing "As a contributor to open-source", through the git alias
```bash
$ git push origin feature
```

> What is the git remote configuration for REMOTE?

Included in the reproduction, restated here for convenience
```bash
$ git remote -vv
origin	git@github.com:lestephane/hub.git (fetch)
origin	git@github.com:lestephane/hub.git (push)
upstream	git://github.com/github/hub.git (fetch)
upstream	git://github.com/github/hub.git (push)
```
> Are you pushing your branch to a GitHub repository that is a fork?

Yes, since I'm following the way it is described at https://hub.github.com/ for contributing "As a contributor to open-source", which says I should do

```bash
$ git fork --remote-name=origin`
```

Which I did (see reproduction)

> What is the exact error that you get as a result of hub pull-request? You can set HUB_VERBOSE=1 to get more debugging output.

The output of `$ HUB_VERBOSE=1 git pull-request` is as follows:

```
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse --symbolic-full-name feature@{upstream}
$ git config branch.feature.remote
$ git rev-parse -q --git-path refs/remotes/origin/feature
> GET https://api.github.com/repos/github/hub
> Authorization: token [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
< HTTP 200
{"id":401025,"node_id":"MDEwOlJlcG9zaXRvcnk0MDEwMjU=","name":"hub","full_name":"github/hub","private":false,"owner":{"login":"github","id":9919,"node_id":"MDEyOk9yZ2FuaXphdGlvbjk5MTk=","avatar_url":"https://avatars1.githubusercontent.com/u/9919?v=4","gravatar_id":"","url":"https://api.github.com/users/github","html_url":"https://github.com/github","followers_url":"https://api.github.com/users/github/followers","following_url":"https://api.github.com/users/github/following{/other_user}","gists_url":"https://api.github.com/users/github/gists{/gist_id}","starred_url":"https://api.github.com/users/github/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github/subscriptions","organizations_url":"https://api.github.com/users/github/orgs","repos_url":"https://api.github.com/users/github/repos","events_url":"https://api.github.com/users/github/events{/privacy}","received_events_url":"https://api.github.com/users/github/received_events","type":"Organization","site_admin":false},"html_url":"https://github.com/github/hub","description":"A command-line tool that makes git easier to use with GitHub.","fork":false,"url":"https://api.github.com/repos/github/hub","forks_url":"https://api.github.com/repos/github/hub/forks","keys_url":"https://api.github.com/repos/github/hub/keys{/key_id}","collaborators_url":"https://api.github.com/repos/github/hub/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/github/hub/teams","hooks_url":"https://api.github.com/repos/github/hub/hooks","issue_events_url":"https://api.github.com/repos/github/hub/issues/events{/number}","events_url":"https://api.github.com/repos/github/hub/events","assignees_url":"https://api.github.com/repos/github/hub/assignees{/user}","branches_url":"https://api.github.com/repos/github/hub/branches{/branch}","tags_url":"https://api.github.com/repos/github/hub/tags","blobs_url":"https://api.github.com/repos/github/hub/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/github/hub/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/github/hub/git/refs{/sha}","trees_url":"https://api.github.com/repos/github/hub/git/trees{/sha}","statuses_url":"https://api.github.com/repos/github/hub/statuses/{sha}","languages_url":"https://api.github.com/repos/github/hub/languages","stargazers_url":"https://api.github.com/repos/github/hub/stargazers","contributors_url":"https://api.github.com/repos/github/hub/contributors","subscribers_url":"https://api.github.com/repos/github/hub/subscribers","subscription_url":"https://api.github.com/repos/github/hub/subscription","commits_url":"https://api.github.com/repos/github/hub/commits{/sha}","git_commits_url":"https://api.github.com/repos/github/hub/git/commits{/sha}","comments_url":"https://api.github.com/repos/github/hub/comments{/number}","issue_comment_url":"https://api.github.com/repos/github/hub/issues/comments{/number}","contents_url":"https://api.github.com/repos/github/hub/contents/{+path}","compare_url":"https://api.github.com/repos/github/hub/compare/{base}...{head}","merges_url":"https://api.github.com/repos/github/hub/merges","archive_url":"https://api.github.com/repos/github/hub/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/github/hub/downloads","issues_url":"https://api.github.com/repos/github/hub/issues{/number}","pulls_url":"https://api.github.com/repos/github/hub/pulls{/number}","milestones_url":"https://api.github.com/repos/github/hub/milestones{/number}","notifications_url":"https://api.github.com/repos/github/hub/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/github/hub/labels{/name}","releases_url":"https://api.github.com/repos/github/hub/releases{/id}","deployments_url":"https://api.github.com/repos/github/hub/deployments","created_at":"2009-12-05T22:15:25Z","updated_at":"2019-07-03T09:52:50Z","pushed_at":"2019-07-02T14:58:51Z","git_url":"git://github.com/github/hub.git","ssh_url":"git@github.com:github/hub.git","clone_url":"https://github.com/github/hub.git","svn_url":"https://github.com/github/hub","homepage":"https://hub.github.com/","size":6213,"stargazers_count":16573,"watchers_count":16573,"language":"Go","has_issues":true,"has_projects":true,"has_downloads":false,"has_wiki":false,"has_pages":true,"forks_count":1670,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":188,"license":{"key":"mit","name":"MIT License","spdx_id":"MIT","url":"https://api.github.com/licenses/mit","node_id":"MDc6TGljZW5zZTEz"},"forks":1670,"open_issues":188,"watchers":16573,"default_branch":"master","permissions":{"admin":false,"push":false,"pull":true},"organization":{"login":"github","id":9919,"node_id":"MDEyOk9yZ2FuaXphdGlvbjk5MTk=","avatar_url":"https://avatars1.githubusercontent.com/u/9919?v=4","gravatar_id":"","url":"https://api.github.com/users/github","html_url":"https://github.com/github","followers_url":"https://api.github.com/users/github/followers","following_url":"https://api.github.com/users/github/following{/other_user}","gists_url":"https://api.github.com/users/github/gists{/gist_id}","starred_url":"https://api.github.com/users/github/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github/subscriptions","organizations_url":"https://api.github.com/users/github/orgs","repos_url":"https://api.github.com/users/github/repos","events_url":"https://api.github.com/users/github/events{/privacy}","received_events_url":"https://api.github.com/users/github/received_events","type":"Organization","site_admin":false},"network_count":1670,"subscribers_count":328}
$ git rev-list --cherry-pick --right-only --no-merges upstream/master...upstream/feature
$ git rev-parse --show-toplevel
$ git var GIT_EDITOR
$ git config core.commentchar
$ vim --cmd set ft=gitcommit tw=0 wrap lbr /home/lestephane/GitRepos/hub/.git/PULLREQ_EDITMSG
> POST https://api.github.com/repos/github/hub/pulls
> Authorization: token [REDACTED]
> Accept: application/vnd.github.shadow-cat-preview+json;charset=utf-8
{"base":"master","head":"github:feature","maintainer_can_modify":true,"title":"Please ignore this pull request, attempting to come up with the reproduction steps from the problem I experienced in #189"}
< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

**Comment by ohcibi** [comment]
@Lestaphane you have to **track** your feature branch. It’s not a bug but a common error users do because of missing documentation.

    git push -u origin your-branch

Instead of simply git push

**Comment by mislav** [comment]
@ohcibi This is precisely what @lestephane is reporting here: we either have to fix the docs, or we shoud make hub work without the `-u`. But, I thought the latter already works. I will look deeper into this.

Thank you for the detailed reproduction steps! ❤️

**Comment by Sameshaik** [comment]
Why
